# Generated by Django 6.0.7 on 2026-08-07 12:46

import apps.users.user_manager
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('group', models.CharField(db_index=True, default='general', max_length=100, verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Ruxsat',
                'verbose_name_plural': 'Ruxsatlar',
                'db_table': 'permission_code',
                'ordering': ['group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Login')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Otasining ismi')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('telegram_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — barcha viloyatlarni ko'radi", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='regions.region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='regions.zone')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', apps.users.user_manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_key', models.CharField(blank=True, default='', max_length=500)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yuz profili',
                'verbose_name_plural': 'Yuz profillari',
                'db_table': 'user_face_profile',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('key', models.IntegerField(unique=True, verbose_name='Kalit')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Izoh')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'db_table': 'roles',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['region', 'is_active'], name='idx_user_region_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
    ]
