# Generated by Django 6.0.7 on 2026-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_global',
            field=models.BooleanField(default=False, help_text="Yoqilsa - bu roldagi xodim barcha viloyatlarni ko'radi", verbose_name="Butun respublika bo'yicha"),
        ),
    ]
