# Generated by Django 6.0.7 on 2026-09-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
        ('users', '0003_drop_superadmin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Viloyat darajasidagi rol uchun MAJBURIY — bo'sh bo'lsa xodim admin panelda hech narsa ko'rmaydi. Butun respublika: rolda", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='regions.region'),
        ),
    ]
