# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mac', message="MAC manzil formati noto'g'ri (AA:BB:CC:DD:EE:FF)", regex=re.compile('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$'))], verbose_name='MAC manzil')),
                ('rtsp_path', models.CharField(blank=True, default='/Streaming/Channels/101', max_length=255)),
                ('login', models.CharField(blank=True, default='', max_length=120)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Xatolik')], db_index=True, default='offline', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='regions.zone')),
            ],
            options={
                'verbose_name': 'IP kamera',
                'verbose_name_plural': 'IP kameralar',
                'db_table': 'camera',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inventory_code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_inventory_code', message="Inventar kodi faqat harf, raqam, `-` va `_` dan iborat bo'lishi kerak", regex='^[A-Za-z0-9_\\-]{3,50}$')], verbose_name='Inventar kodi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mac', message="MAC manzil formati noto'g'ri (AA:BB:CC:DD:EE:FF)", regex=re.compile('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$'))], verbose_name='MAC manzil')),
                ('info_pc', models.JSONField(blank=True, null=True, verbose_name="Qurilma ma'lumotlari")),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('in_exam', 'Imtihonda'), ('blocked', 'Bloklangan')], db_index=True, default='offline', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cameras', models.ManyToManyField(blank=True, related_name='computers', to='devices.camera')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='regions.zone')),
            ],
            options={
                'verbose_name': 'Kompyuter',
                'verbose_name_plural': 'Kompyuterlar',
                'db_table': 'computer',
                'ordering': ['zone', 'inventory_code'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='Qurilma ID')),
                ('secret_hash', models.CharField(max_length=128)),
                ('hardware_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('app_hash', models.CharField(blank=True, default='', help_text="Client binary SHA-256 — o'zgargani anomaliya sifatida belgilanadi", max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Tasdiqlanmagan'), ('active', 'Faol'), ('revoked', 'Bekor qilingan')], db_index=True, default='pending', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='devices.computer')),
            ],
            options={
                'verbose_name': 'Qurilma tokeni',
                'verbose_name_plural': 'Qurilma tokenlari',
                'db_table': 'device_token',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['zone', 'status'], name='idx_camera_zone_status'),
        ),
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['zone', 'status'], name='idx_computer_zone_status'),
        ),
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['status', 'last_seen_at'], name='idx_computer_heartbeat'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('zone', 'ip_address'), name='unique_computer_zone_ip'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['status', 'last_used_at'], name='idx_device_status_used'),
        ),
    ]
