# Generated by Django 6.0.7 on 2026-08-13 16:19

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_mac', message="MAC manzil formati noto'g'ri (AA:BB:CC:DD:EE:FF)", regex=re.compile('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$'))], verbose_name='MAC manzil'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inventory_code',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_inventory_code', message="Inventar kodi faqat harf, raqam, `-` va `_` dan iborat bo'lishi kerak", regex='^[A-Za-z0-9_\\-]{3,50}$')], verbose_name='Inventar kodi'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_mac', message="MAC manzil formati noto'g'ri (AA:BB:CC:DD:EE:FF)", regex=re.compile('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$'))], verbose_name='MAC manzil'),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('mac_address',), name='unique_camera_mac'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('inventory_code',), name='unique_computer_inventory_code'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('mac_address',), name='unique_computer_mac'),
        ),
    ]
