# Generated by Django 6.0.7 on 2026-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_conditional_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='secret_hash',
        ),
    ]
