# Generated by Django 6.0.7 on 2026-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_jwt_client_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='reported_public_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
