# Generated by Django 6.0.7 on 2026-09-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_reported_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.PositiveIntegerField(default=554, verbose_name='RTSP port'),
        ),
        migrations.AddField(
            model_name='camera',
            name='transport',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=8, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='camera',
            name='vendor',
            field=models.CharField(choices=[('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('onvif', 'ONVIF (umumiy)'), ('generic', 'Boshqa')], default='hikvision', max_length=32, verbose_name='Ishlab chiqaruvchi'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='gpu_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='performance_profile',
            field=models.CharField(blank=True, db_index=True, default='', help_text="high / medium / low / cpu / minimal — client o'zi aniqlaydi", max_length=8, verbose_name='Unumdorlik profili'),
        ),
        migrations.CreateModel(
            name='CameraAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Birlamchi (yuz)'), ('secondary', 'Ikkilamchi (stol/xona)')], max_length=10, verbose_name='Rol')),
                ('source', models.CharField(choices=[('ip', 'IP kamera'), ('local', 'Lokal veb-kamera')], default='local', max_length=8, verbose_name='Manba')),
                ('local_index', models.PositiveSmallIntegerField(blank=True, help_text='Lokal kamera uchun: 0 — birinchi qurilma', null=True, verbose_name='Qurilma indeksi')),
                ('is_required', models.BooleanField(default=True, help_text='Bu kamera ishlamasa imtihon boshlanmaydi (siyosat ruxsat bersa)', verbose_name='Majburiy')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='devices.camera', verbose_name='Kamera')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_assignments', to='devices.computer', verbose_name='Kompyuter')),
            ],
            options={
                'verbose_name': 'Kamera biriktirish',
                'verbose_name_plural': 'Kamera biriktirishlari',
                'db_table': 'camera_assignment',
                'ordering': ['computer', 'role'],
                'indexes': [models.Index(fields=['computer', 'role'], name='idx_cam_assign_computer')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('computer', 'role'), name='unique_camera_assignment_role'), models.CheckConstraint(condition=models.Q(models.Q(('camera__isnull', False), ('source', 'ip')), models.Q(('camera__isnull', True), ('source', 'local')), _connector='OR'), name='camera_assignment_source_matches')],
            },
        ),
    ]
