# Generated by Django 6.0.7 on 2026-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_drop_camera_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='reported_lan_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
