# Generated by Django 6.0.7 on 2026-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_lan_ip'),
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['zone', 'number', 'inventory_code'], 'verbose_name': 'Kompyuter', 'verbose_name_plural': 'Kompyuterlar'},
        ),
        migrations.AddField(
            model_name='computer',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Raqami'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('number__isnull', False)), fields=('zone', 'number'), name='unique_computer_zone_number'),
        ),
    ]
