# Generated by Django 6.0.7 on 2026-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_computer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
