# Generated by Django 6.0.7 on 2026-09-25 06:36

from django.db import migrations, models


def placeholder_to_null(apps, schema_editor):
    # Avtomatik inventarizatsiya IP bo'lmaganda "0.0.0.0" yozardi. U
    # manzil emas, "noma'lum" belgisi edi - endi buning uchun NULL bor.
    Computer = apps.get_model("devices", "Computer")
    Computer.objects.filter(ip_address="0.0.0.0").update(ip_address=None)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_camera_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.RunPython(placeholder_to_null, migrations.RunPython.noop),
    ]
