# Generated by Django 6.0.7 on 2026-09-26 05:54

import apps.common.utils.validators
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_computer_ip_optional'),
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='computer',
            name='unique_computer_mac',
        ),
        migrations.AddField(
            model_name='computer',
            name='machine_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[apps.common.utils.validators.machine_uuid_validator], verbose_name='Machine UUID'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='reported_machine_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_mac', message="MAC manzil formati noto'g'ri (AA:BB:CC:DD:EE:FF)", regex=re.compile('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$'))], verbose_name='MAC manzil'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('machine_uuid__isnull', False)), fields=('machine_uuid',), name='unique_computer_machine_uuid'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('mac_address', ''), _negated=True)), fields=('mac_address',), name='unique_computer_mac'),
        ),
    ]
