# Generated by Django 6.0.7 on 2026-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_computer_machine_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='reported_mac',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
