# Generated by Django 6.0.7 on 2026-09-30 14:49

import re

from django.db import migrations, models

#: `apps.common.utils.validators.normalize_mac` bilan bir xil qoida. Nusxa
#: ATAYLAB: migratsiya yozilgan paytdagi qoidada qolishi kerak, keyin
#: o'zgargan funksiya eski migratsiyani boshqacha ishlatib yubormasin.
_MAC_RE = re.compile(r"^([0-9A-F]{2}:){5}[0-9A-F]{2}$")


def _normalize(value):
    cleaned = str(value or "").replace("-", ":").upper().strip()
    return cleaned if _MAC_RE.match(cleaned) else None


def normalize_computer_macs(apps, schema_editor):
    """
    Mavjud MAC'larni kanonik shaklga (`AA:BB:CC:DD:EE:FF`) keltiradi.

    Juftlik bo'yicha qidiruv (`find_computer_by_identity`) va yangi
    cheklov bir xil yozilgan qiymatga tayanadi: `2c-f0-...` va
    `2C:F0:...` bazada ikki xil satr - cheklov ularni ajratmasdi.

    Yiqilmaslik uchun ikki holat O'TKAZIB YUBORILADI (qator o'zgarmaydi):
    yaroqsiz qiymat va kanonik shakli boshqa tirik yozuvda band bo'lgan
    qiymat (`unique_computer_mac`). Ularni administrator hal qiladi -
    `audit_machine_identity` ko'rsatadi.
    """
    Computer = apps.get_model("devices", "Computer")
    rows = Computer.objects.exclude(mac_address="").values_list("pk", "mac_address", "deleted_at")
    for pk, value, deleted_at in rows.iterator():
        canonical = _normalize(value)
        if canonical is None or canonical == value:
            continue
        if deleted_at is None and (
            Computer.objects.filter(deleted_at__isnull=True, mac_address=canonical)
            .exclude(pk=pk)
            .exists()
        ):
            continue
        Computer.objects.filter(pk=pk).update(mac_address=canonical)


class Migration(migrations.Migration):
    """
    Kompyuter identifikatori - (machine_uuid, mac_address) JUFTLIGI.

    `unique_computer_machine_uuid` olib tashlanadi: arzon platalarda SMBIOS
    UUID bir partiyada bir xil va bunday ikkinchi mashinani qo'shib
    bo'lmasdi. Mavjud ma'lumotda yiqilmaydi: hozirgacha UUID unikal edi,
    demak juftliklar ham unikal.
    """

    dependencies = [
        ('devices', '0012_devicetoken_reported_mac'),
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_computer_macs, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='computer',
            name='unique_computer_machine_uuid',
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('machine_uuid__isnull', False), models.Q(('mac_address', ''), _negated=True)), fields=('machine_uuid', 'mac_address'), name='unique_computer_uuid_mac'),
        ),
    ]
