# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Kalit')),
                ('external_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Tashqi platforma kodi')),
                ('site_url', models.URLField(default='https://ntest.uzbmb.uz/login', max_length=500, verbose_name='Test platformasi URL')),
                ('allowed_domains', models.JSONField(blank=True, default=list, verbose_name='Ruxsat etilgan domenlar')),
                ('duration_minutes', models.PositiveIntegerField(default=180, verbose_name='Davomiyligi (daq)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('setting', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — global faol sozlama ishlatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='controls.setting')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
                'db_table': 'exams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exam_date', models.DateField(db_index=True, verbose_name='Sana')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanishi')),
                ('ends_at', models.DateTimeField(verbose_name='Tugashi')),
                ('checkin_lead_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam')),
                ('zone', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — barcha binolar uchun", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='regions.zone')),
            ],
            options={
                'verbose_name': 'Imtihon jadvali',
                'verbose_name_plural': 'Imtihon jadvallari',
                'db_table': 'exam_schedule',
                'ordering': ['-exam_date', 'starts_at'],
                'indexes': [models.Index(fields=['exam_date', 'is_active'], name='idx_schedule_date_active'), models.Index(fields=['zone', 'exam_date'], name='idx_schedule_zone_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='exam_schedule_ends_after_starts')],
            },
        ),
    ]
