# Generated by Django 6.0.7 on 2026-08-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['id'], 'verbose_name': 'Imtihon', 'verbose_name_plural': 'Imtihonlar'},
        ),
    ]
