# Generated by Django 6.0.7 on 2026-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_conditional_unique'),
        ('exams', '0002_alter_exam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_exam_name'),
        ),
    ]
