# Generated by Django 6.0.7 on 2026-09-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_conditional_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='Kalit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Imtihon turi',
                'verbose_name_plural': 'Imtihon turlari',
                'db_table': 'exam_type',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_exam_type_name'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('key',), name='unique_exam_type_key')],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.examtype', verbose_name='Imtihon turi'),
        ),
    ]
