# Generated by Django 6.0.7 on 2026-09-23 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_camera_status'),
        ('exams', '0005_exam_site_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ishchi holatda')),
                ('is_booked', models.BooleanField(db_index=True, default=False, verbose_name='Band')),
                ('pinfl', models.CharField(blank=True, db_index=True, default='', max_length=14, verbose_name='JSHSHIR')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Biriktirilgan vaqt')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim biriktirgan')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='devices.computer', verbose_name='Kompyuter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='exams.examschedule', verbose_name='Test sessiyasi')),
            ],
            options={
                'verbose_name': 'Kompyuter broni',
                'verbose_name_plural': 'Kompyuter bronlari',
                'db_table': 'computer_booking',
                'ordering': ['schedule', 'computer__zone', 'computer__number', 'computer__inventory_code'],
                'indexes': [models.Index(fields=['schedule', 'is_booked'], name='idx_booking_schedule_booked')],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'computer'), name='unique_booking_schedule_computer'), models.UniqueConstraint(condition=models.Q(('pinfl', ''), _negated=True), fields=('schedule', 'pinfl'), name='unique_booking_schedule_pinfl'), models.CheckConstraint(condition=models.Q(models.Q(('is_booked', True), models.Q(('pinfl', ''), _negated=True)), models.Q(('is_booked', False), ('pinfl', '')), _connector='OR'), name='booking_pinfl_matches_flag')],
            },
        ),
    ]
