# Generated by Django 6.0.7 on 2026-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_booking_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerbooking',
            name='finished_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yakunlaganlar soni'),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi yakun'),
        ),
    ]
