# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('dtm_id', models.IntegerField(unique=True, verbose_name='DTM ID')),
                ('vm_number', models.IntegerField(unique=True, verbose_name='VM raqami')),
                ('is_have_part', models.BooleanField(default=False, verbose_name="Bo'linmalari bor")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'db_table': 'region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('number', models.IntegerField(default=0, verbose_name='Raqam')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Manzil')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'im")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_part', models.BooleanField(default=False, verbose_name='Bino ankladi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='regions.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'db_table': 'zone',
                'ordering': ['region__name', 'number'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='idx_zone_region_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('region', 'number'), name='unique_zone_region_number')],
            },
        ),
    ]
