# Generated by Django 6.0.7 on 2026-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['dtm_id'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['region__dtm_id', 'number'], 'verbose_name': 'Bino', 'verbose_name_plural': 'Binolar'},
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_part',
            field=models.BooleanField(default=False, verbose_name='Bino anklabmi'),
        ),
    ]
