# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocoObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'COCO obyekt guruhi',
                'verbose_name_plural': 'COCO obyekt guruhlari',
                'db_table': 'coco_object_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HotKeyboardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tezkor tugma',
                'verbose_name_plural': 'Tezkor tugmalar',
                'db_table': 'hot_keyboard_key',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('file_key', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Model versiyasi',
                'verbose_name_plural': 'Model versiyalari',
                'db_table': 'model_version',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RdpObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('process_names', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RDP dastur',
                'verbose_name_plural': 'RDP dasturlar',
                'db_table': 'rdp',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AllowedPublicIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to='regions.zone')),
            ],
            options={
                'verbose_name': 'Ruxsat etilgan IP',
                'verbose_name_plural': "Ruxsat etilgan IP'lar",
                'db_table': 'allowed_public_ip',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='CocoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('severity', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coco_objects', to='controls.cocoobjectgroup')),
            ],
            options={
                'verbose_name': 'COCO obyekt',
                'verbose_name_plural': 'COCO obyektlar',
                'db_table': 'coco_object',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExitPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('zone', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — global", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_passwords', to='regions.zone')),
            ],
            options={
                'verbose_name': 'Chiqish paroli',
                'verbose_name_plural': 'Chiqish parollari',
                'db_table': 'exit_password',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['zone', 'is_active'], name='idx_exitpwd_zone_active')],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('mode', models.PositiveSmallIntegerField(default=0, verbose_name='Rejim')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Faol')),
                ('is_faceid_staff', models.BooleanField(default=False, verbose_name='Xodim yuz tekshiruvi')),
                ('is_faceid_student', models.BooleanField(default=True, verbose_name='Talabgor yuz tekshiruvi')),
                ('is_faceid_exam', models.BooleanField(default=True, verbose_name='Test davomida yuz tekshiruvi')),
                ('faceid_interval', models.PositiveSmallIntegerField(default=10, verbose_name='Interval (s)')),
                ('faceid_max_fail', models.PositiveSmallIntegerField(default=3, verbose_name='Maks. muvaffaqiyatsiz urinish')),
                ('warning_timeout', models.PositiveSmallIntegerField(default=5, verbose_name='Ogohlantirish kutish vaqti (s)')),
                ('faceid_min_score_staff', models.PositiveSmallIntegerField(default=70, verbose_name='Min ball (xodim)')),
                ('faceid_min_score_student', models.PositiveSmallIntegerField(default=70, verbose_name='Min ball (talabgor)')),
                ('faceid_min_score_exam', models.PositiveSmallIntegerField(default=70, verbose_name='Min ball (test)')),
                ('faceid_audit_rate', models.FloatField(default=0.05, verbose_name='Server auditi ulushi')),
                ('is_screen_record', models.BooleanField(default=False, verbose_name='Ekranni yozish')),
                ('is_detect_monitor', models.BooleanField(default=True, verbose_name='Monitor tekshiruvi')),
                ('is_detect_camera', models.BooleanField(default=True, verbose_name='Kamera tekshiruvi')),
                ('screenshot_interval', models.PositiveSmallIntegerField(default=10, verbose_name='Skrinshot intervali (s)')),
                ('screenshot_quality', models.PositiveSmallIntegerField(default=65, verbose_name='Skrinshot sifati')),
                ('screenshot_max_width', models.PositiveSmallIntegerField(default=960, verbose_name='Maks. kenglik')),
                ('screenshot_dedup_threshold', models.PositiveSmallIntegerField(default=6, verbose_name='Dedup chegarasi')),
                ('is_enable_detect', models.BooleanField(default=False, verbose_name='Obyekt aniqlash')),
                ('detect_confidence', models.FloatField(default=0.5, verbose_name='Ishonch chegarasi')),
                ('detect_frame_skip', models.PositiveSmallIntegerField(default=20, verbose_name="Kadr o'tkazish")),
                ('is_enable_rdp_detect', models.BooleanField(default=True, verbose_name='RDP aniqlash')),
                ('is_enable_check_tp', models.BooleanField(default=True, verbose_name='Texnik muammoni tekshirish')),
                ('heartbeat_interval', models.PositiveSmallIntegerField(default=30, verbose_name='Heartbeat intervali (s)')),
                ('event_batch_interval', models.PositiveSmallIntegerField(default=5, verbose_name='Event batch intervali (s)')),
                ('offline_buffer_size', models.PositiveIntegerField(default=5000, verbose_name='Offline buffer hajmi')),
                ('detect_classes', models.ManyToManyField(blank=True, related_name='settings', to='controls.cocoobject')),
                ('detect_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.modelversion')),
                ('hotkeys', models.ManyToManyField(blank=True, related_name='settings', to='controls.hotkeyboardkey')),
                ('rdp_objects', models.ManyToManyField(blank=True, related_name='settings', to='controls.rdpobject')),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
                'db_table': 'settings',
                'ordering': ['mode', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('mode',), name='unique_setting_mode'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('is_active',), name='unique_active_setting')],
            },
        ),
    ]
