# Generated by Django 6.0.7 on 2026-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_remove_staff_faceid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['name'], 'verbose_name': 'Sozlama', 'verbose_name_plural': 'Sozlamalar'},
        ),
        migrations.RemoveConstraint(
            model_name='setting',
            name='unique_setting_mode',
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Global standart'),
        ),
        migrations.RemoveField(
            model_name='setting',
            name='mode',
        ),
    ]
