# Generated by Django 6.0.7 on 2026-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_conditional_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exitpassword',
            name='idx_exitpwd_zone_active',
        ),
        migrations.DeleteModel(
            name='ExitPassword',
        ),
    ]
