# Generated by Django 6.0.7 on 2026-09-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_jwt_client_auth'),
        ('regions', '0002_alter_region_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExitPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('password', models.CharField(max_length=255, verbose_name='Parol')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_password', to='regions.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Chiqish paroli',
                'verbose_name_plural': 'Chiqish parollari',
                'db_table': 'client_exit_password',
                'ordering': ['region__dtm_id'],
            },
        ),
    ]
