# Generated by Django 6.0.7 on 2026-09-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_client_exit_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRiskWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=48, unique=True, verbose_name='Hodisa turi')),
                ('weight', models.PositiveSmallIntegerField(default=5, verbose_name="Og'irlik")),
                ('severity', models.PositiveSmallIntegerField(default=1, verbose_name='Jiddiylik')),
                ('cooldown_s', models.PositiveSmallIntegerField(default=0, help_text='0 — siyosatdagi umumiy qiymat ishlatiladi', verbose_name="Takror oralig'i (s)")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Hodisa og'irligi",
                'verbose_name_plural': "Hodisa og'irliklari",
                'db_table': 'event_risk_weight',
                'ordering': ['-weight', 'event_type'],
            },
        ),
        migrations.AddField(
            model_name='cocoobject',
            name='risk_weight',
            field=models.PositiveSmallIntegerField(default=15, help_text="Aniqlanganda xavf balliga qo'shiladi (0-100)", verbose_name="Xavf og'irligi"),
        ),
        migrations.CreateModel(
            name='ProctoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='AI proktorlik yoqilgan')),
                ('camera_count', models.PositiveSmallIntegerField(default=1, verbose_name='Kameralar soni')),
                ('primary_camera_kind', models.CharField(choices=[('auto', 'Ixtiyoriy (biriktirishga qarab)'), ('local', 'Lokal veb-kamera'), ('ip', 'IP kamera')], default='auto', max_length=8, verbose_name='Birlamchi kamera turi')),
                ('secondary_camera_kind', models.CharField(choices=[('auto', 'Ixtiyoriy (biriktirishga qarab)'), ('local', 'Lokal veb-kamera'), ('ip', 'IP kamera')], default='auto', max_length=8, verbose_name='Ikkilamchi kamera turi')),
                ('primary_required', models.BooleanField(default=True, verbose_name='Birlamchi majburiy')),
                ('secondary_required', models.BooleanField(default=False, verbose_name='Ikkilamchi majburiy')),
                ('allow_virtual_camera', models.BooleanField(default=False, verbose_name='Virtual kameraga ruxsat')),
                ('min_fps', models.PositiveSmallIntegerField(default=12, verbose_name='Minimal FPS')),
                ('min_width', models.PositiveSmallIntegerField(default=640, verbose_name='Minimal kenglik')),
                ('min_height', models.PositiveSmallIntegerField(default=480, verbose_name='Minimal balandlik')),
                ('camera_lost_grace_s', models.PositiveSmallIntegerField(default=30, verbose_name='Kamera uzilishiga chidam (s)')),
                ('camera_lost_action', models.CharField(choices=[('warn', 'Ogohlantirish'), ('pause', "Imtihonni to'xtatib turish"), ('terminate', 'Chetlashtirish')], default='warn', max_length=10, verbose_name='Kamera uzilganda')),
                ('enable_identity', models.BooleanField(default=True, verbose_name='Shaxs (FaceID)')),
                ('enable_objects', models.BooleanField(default=True, verbose_name='Obyekt aniqlash (YOLO)')),
                ('enable_pose', models.BooleanField(default=False, verbose_name="Poza va qo'llar")),
                ('enable_gaze', models.BooleanField(default=True, verbose_name='Nigoh va bosh holati')),
                ('enable_tracking', models.BooleanField(default=True, verbose_name='Obyekt kuzatuvi (ByteTrack)')),
                ('identity_fps', models.PositiveSmallIntegerField(default=10, verbose_name='Shaxs FPS')),
                ('object_fps', models.PositiveSmallIntegerField(default=6, verbose_name='Obyekt FPS')),
                ('pose_fps', models.PositiveSmallIntegerField(default=8, verbose_name='Poza FPS')),
                ('gaze_fps', models.PositiveSmallIntegerField(default=10, verbose_name='Nigoh FPS')),
                ('gpu_profile_override', models.CharField(choices=[('auto', 'Avtomatik (client aniqlaydi)'), ('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past'), ('cpu', 'Faqat CPU'), ('minimal', 'Minimal (faqat yuz)')], default='auto', help_text="`auto` — client apparatni o'zi aniqlaydi", max_length=8, verbose_name='Unumdorlik profili')),
                ('no_face_warn_s', models.PositiveSmallIntegerField(default=2, verbose_name="Yuz yo'q — ogohlantirish (s)")),
                ('no_face_suspicious_s', models.PositiveSmallIntegerField(default=5, verbose_name="Yuz yo'q — shubha (s)")),
                ('gaze_away_warn_s', models.PositiveSmallIntegerField(default=2, verbose_name='Nigoh chetda — ogohlantirish (s)')),
                ('gaze_away_suspicious_s', models.PositiveSmallIntegerField(default=5, verbose_name='Nigoh chetda — shubha (s)')),
                ('object_min_frames', models.PositiveSmallIntegerField(default=5, verbose_name='Obyekt: min kadr')),
                ('object_min_conf', models.FloatField(default=0.8, verbose_name='Obyekt: min ishonch')),
                ('object_min_duration_ms', models.PositiveIntegerField(default=1200, verbose_name='Obyekt: min davomiylik (ms)')),
                ('fusion_window_ms', models.PositiveIntegerField(default=3000, verbose_name='Birlashtirish oynasi (ms)')),
                ('risk_decay_per_min', models.PositiveSmallIntegerField(default=5, verbose_name='Ball pasayishi (daq)')),
                ('risk_event_cooldown_s', models.PositiveSmallIntegerField(default=60, help_text="Shu oraliq ichidagi takror hodisa ballga qo'shilmaydi", verbose_name="Bir xil hodisa oralig'i (s)")),
                ('threshold_low', models.PositiveSmallIntegerField(default=20, verbose_name='Past chegara')),
                ('threshold_medium', models.PositiveSmallIntegerField(default=40, verbose_name="O'rta chegara")),
                ('threshold_high', models.PositiveSmallIntegerField(default=70, verbose_name='Yuqori chegara')),
                ('evidence_enabled', models.BooleanField(default=True, verbose_name="Dalil to'plash")),
                ('evidence_clip_seconds', models.PositiveSmallIntegerField(default=5, verbose_name='Klip uzunligi (s)')),
                ('evidence_min_severity', models.PositiveSmallIntegerField(default=2, verbose_name='Min jiddiylik')),
                ('evidence_clip_retention_days', models.PositiveSmallIntegerField(default=30, verbose_name='Klip saqlash (kun)')),
                ('evidence_frame_retention_days', models.PositiveSmallIntegerField(default=90, verbose_name='Kadr saqlash (kun)')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='controls.setting', verbose_name='Sozlama profili')),
            ],
            options={
                'verbose_name': 'Proktorlik siyosati',
                'verbose_name_plural': 'Proktorlik siyosatlari',
                'db_table': 'proctoring_policy',
                'ordering': ['setting__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_low__lt', models.F('threshold_medium')), ('threshold_medium__lt', models.F('threshold_high'))), name='proctoring_policy_thresholds_ordered'), models.CheckConstraint(condition=models.Q(('camera_count__gte', 1), ('camera_count__lte', 2)), name='proctoring_policy_camera_count')],
            },
        ),
    ]
