# Generated by Django 6.0.7 on 2026-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_score_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdpobject',
            name='category',
            field=models.CharField(choices=[('remote', 'Masofaviy boshqaruv'), ('vm', 'Virtual mashina'), ('tool', 'Yordamchi vosita')], default='remote', max_length=16, verbose_name='Toifa'),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='is_blocking',
            field=models.BooleanField(default=False, help_text="Yopib bo'lmasa imtihon boshlanmaydi", verbose_name="Imtihonni to'sadi"),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='original_filenames',
            field=models.JSONField(blank=True, default=list, help_text="PE resursidagi asl nom — faylni qayta nomlash unga ta'sir qilmaydi", verbose_name='OriginalFilename'),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='ports',
            field=models.JSONField(blank=True, default=list, help_text='Tinglanadigan TCP portlar — resursi va imzosi tozalangan binar uchun', verbose_name='Portlar'),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text="ProductName / FileDescription ichidan qism satr bo'yicha qidiriladi", verbose_name='Mahsulot nomlari'),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='publishers',
            field=models.JSONField(blank=True, default=list, help_text='Sertifikatdagi tashkilot nomi, masalan: AnyDesk Software GmbH', verbose_name='Imzo egalari'),
        ),
        migrations.AddField(
            model_name='rdpobject',
            name='service_names',
            field=models.JSONField(blank=True, default=list, help_text="Oynasiz qism shu yerda yashaydi; xizmatsiz jarayonni o'ldirish foydasiz", verbose_name='Windows xizmatlari'),
        ),
    ]
