# Generated by Django 6.0.7 on 2026-09-25 13:56

"""
Skrinshot TAYMERDAN BUYRUQQA o'tdi: test platformasi javob belgilanganda
client lokal xizmatiga buyruq yuboradi (`client/services/local_service.py`).
Interval va dedup ma'nosini yo'qotdi va OLIB TASHLANDI (qolsa panelda
hech narsaga ta'sir qilmaydigan maydon turardi). Yangi bayroq standarti
`True` - mavjud profillarda proktor skrinshotlarni avvalgidek ko'radi.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_client_runtime_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='screenshot_dedup_threshold',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='screenshot_interval',
        ),
        migrations.AddField(
            model_name='setting',
            name='is_screenshot_upload',
            field=models.BooleanField(default=True, help_text="O'chiq bo'lsa skrinshot faqat client mashinasida saqlanadi", verbose_name='Skrinshotni serverga yuborish'),
        ),
    ]
