# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('create', 'Yaratish'), ('update', "O'zgartirish"), ('delete', "O'chirish"), ('session_warn', 'Ogohlantirish'), ('session_terminate', 'Chetlashtirish'), ('session_restore', 'Tiklash'), ('tp_resolve', 'Texnik muammo qarori'), ('setting_change', "Sozlama o'zgarishi"), ('device_revoke', 'Qurilmani bloklash'), ('export', 'Eksport')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit yozuvlari',
                'db_table': 'audit_log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinfl_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='JSHSHIR hash')),
                ('pinfl_enc', models.TextField(blank=True, default='', verbose_name='JSHSHIR (shifrlangan)')),
                ('last_name_enc', models.TextField(blank=True, default='')),
                ('first_name_enc', models.TextField(blank=True, default='')),
                ('middle_name_enc', models.TextField(blank=True, default='')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('photo_key', models.CharField(blank=True, default='', max_length=500)),
                ('reference_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('anonymize_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_anonymized', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Talabgor',
                'verbose_name_plural': 'Talabgorlar',
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('exam_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('face_check', 'Yuz tekshiruvida'), ('ready', 'Tayyor'), ('in_progress', 'Jarayonda'), ('finished', 'Tugatilgan'), ('terminated', 'Chetlashtirilgan'), ('technical_problem', 'Texnik muammo'), ('expired', 'Muddati tugagan')], db_index=True, default='pending', max_length=24)),
                ('token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('face_fail_count', models.PositiveSmallIntegerField(default=0)),
                ('face_check_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('screenshot_count', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('termination_reason', models.CharField(blank=True, default='', max_length=500)),
                ('external_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Imtihon sessiyasi',
                'verbose_name_plural': 'Imtihon sessiyalari',
                'db_table': 'exam_session',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAuthToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tashqi token',
                'verbose_name_plural': 'Tashqi tokenlar',
                'db_table': 'external_auth_token',
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('initial', 'Kirishda'), ('periodic', 'Test davomida'), ('audit', 'Server auditi'), ('manual', 'Proktor tekshiruvi')], default='periodic', max_length=16)),
                ('source', models.CharField(choices=[('client', 'Client (ONNX)'), ('server', 'Server (GPU)')], default='client', max_length=16)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('threshold', models.PositiveSmallIntegerField(default=70)),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('faces_detected', models.PositiveSmallIntegerField(default=1)),
                ('image_key', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yuz tekshiruvi',
                'verbose_name_plural': 'Yuz tekshiruvlari',
                'db_table': 'face_verification_log',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('window_blur', 'Oynadan chiqish'), ('window_focus', 'Oynaga qaytish'), ('fullscreen_exit', "To'liq ekrandan chiqish"), ('hotkey_blocked', 'Tezkor tugma bloklandi'), ('clipboard_blocked', "Nusxa ko'chirish bloklandi"), ('multi_monitor', 'Bir nechta monitor'), ('camera_lost', "Kamera yo'qoldi"), ('camera_blocked', 'Kamera yopilgan'), ('rdp_detected', 'Masofaviy boshqaruv aniqlandi'), ('vm_detected', 'Virtual mashina aniqlandi'), ('process_blacklisted', 'Taqiqlangan dastur'), ('face_not_found', 'Yuz topilmadi'), ('face_mismatch', 'Yuz mos kelmadi'), ('multiple_faces', 'Bir nechta yuz'), ('object_detected', 'Taqiqlangan obyekt'), ('network_lost', 'Tarmoq uzildi'), ('network_restored', 'Tarmoq tiklandi'), ('client_anomaly', 'Client anomaliyasi'), ('navigation_blocked', 'URL bloklandi'), ('proctor_warning', 'Proktor ogohlantirdi'), ('session_terminated', 'Sessiya tugatildi')], db_index=True, max_length=32)),
                ('severity', models.SmallIntegerField(choices=[(0, "Ma'lumot"), (1, 'Past'), (2, "O'rta"), (3, 'Yuqori'), (4, 'Kritik')], default=1)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('screenshot_key', models.CharField(blank=True, default='', max_length=500)),
                ('client_event_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Proktorlik hodisasi',
                'verbose_name_plural': 'Proktorlik hodisalari',
                'db_table': 'proctoring_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenshotMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('screen', 'Ekran'), ('webcam', 'Veb-kamera'), ('ipcam', 'IP kamera')], default='screen', max_length=16)),
                ('object_key', models.CharField(max_length=500)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_committed', models.BooleanField(db_index=True, default=False)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Skrinshot',
                'verbose_name_plural': 'Skrinshotlar',
                'db_table': 'screenshot_meta',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('power', 'Elektr'), ('network', 'Tarmoq'), ('hardware', 'Uskuna'), ('software', 'Dastur'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('overtime', models.DurationField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Qaror qabul qilindi')),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Texnik muammo',
                'verbose_name_plural': 'Texnik muammolar',
                'db_table': 'technical_problem',
                'ordering': ['-started_at'],
            },
        ),
    ]
