# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('exams', '0001_initial'),
        ('proctoring', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='regions.region'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='proctoring.candidate'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='devices.computer'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.devicetoken'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsession',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='regions.zone'),
        ),
        migrations.AddField(
            model_name='externalauthtoken',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_token', to='proctoring.examsession'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to='proctoring.examsession'),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proctoring.examsession'),
        ),
        migrations.AddField(
            model_name='screenshotmeta',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='proctoring.examsession'),
        ),
        migrations.AddField(
            model_name='technicalproblem',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalproblem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_problems', to='proctoring.examsession'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='idx_audit_actor_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id', '-created_at'], name='idx_audit_object'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['is_anonymized', 'anonymize_after'], name='idx_candidate_retention'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['zone', 'status', 'exam_date'], name='idx_session_zone_status'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(condition=models.Q(('status__in', ['in_progress', 'face_check', 'ready'])), fields=['status', '-risk_score'], name='idx_session_risk'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(condition=models.Q(('status', 'in_progress')), fields=['last_heartbeat_at'], name='idx_session_heartbeat'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'exam_date'], name='idx_session_exam_date'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['token_hash'], name='idx_session_token'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('candidate', 'exam', 'exam_date', 'attempt_no'), name='unique_session_attempt'),
        ),
        migrations.AddIndex(
            model_name='faceverificationlog',
            index=models.Index(fields=['session', '-occurred_at'], name='idx_facelog_session_time'),
        ),
        migrations.AddIndex(
            model_name='faceverificationlog',
            index=models.Index(condition=models.Q(('passed', False)), fields=['session'], name='idx_facelog_failed'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', '-occurred_at'], name='idx_event_session_time'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(condition=models.Q(('severity__gte', 3)), fields=['-occurred_at'], name='idx_event_critical'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['type', '-occurred_at'], name='idx_event_type_time'),
        ),
        migrations.AddConstraint(
            model_name='proctoringevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('session', 'client_event_id'), name='unique_session_client_event'),
        ),
        migrations.AddIndex(
            model_name='screenshotmeta',
            index=models.Index(fields=['session', '-captured_at'], name='idx_shot_session_time'),
        ),
        migrations.AddIndex(
            model_name='screenshotmeta',
            index=models.Index(fields=['is_committed', 'purge_after'], name='idx_shot_purge'),
        ),
        migrations.AddIndex(
            model_name='technicalproblem',
            index=models.Index(fields=['session', '-started_at'], name='idx_tp_session_time'),
        ),
        migrations.AddIndex(
            model_name='technicalproblem',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['-started_at'], name='idx_tp_unresolved'),
        ),
    ]
