# Generated by Django 6.0.7 on 2026-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_session_owns_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('create', 'Yaratish'), ('update', "O'zgartirish"), ('delete', "O'chirish"), ('session_warn', 'Ogohlantirish'), ('session_terminate', 'Chetlashtirish'), ('session_restore', 'Tiklash'), ('identity_confirm', 'Shaxs tasdiqlandi'), ('identity_reject', 'Shaxs tasdiqlanmadi'), ('tp_resolve', 'Texnik muammo qarori'), ('setting_change', "Sozlama o'zgarishi"), ('device_revoke', 'Qurilmani bloklash'), ('export', 'Eksport')], db_index=True, max_length=32),
        ),
    ]
