# Generated by Django 6.0.7 on 2026-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_jwt_client_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='external_access_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='external_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='external_session_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='examsession',
            name='external_status',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Tashqi platformadagi status'),
        ),
        migrations.DeleteModel(
            name='ExternalAuthToken',
        ),
    ]
