# Generated by Django 6.0.7 on 2026-08-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0007_platform_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringScreenshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500, unique=True, verbose_name="Fayl yo'li")),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=64, verbose_name='MIME turi')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='Olingan vaqti')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Qabul qilingan vaqti')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_screenshots', to='proctoring.examsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Skrinshot (fayl)',
                'verbose_name_plural': 'Skrinshotlar (fayl)',
                'db_table': 'proctoring_screenshot',
                'ordering': ['-captured_at', '-seq'],
                'indexes': [models.Index(fields=['session', '-captured_at'], name='idx_pshot_session_time'), models.Index(fields=['captured_at'], name='idx_pshot_retention')],
                'constraints': [models.UniqueConstraint(fields=('session', 'captured_at', 'seq'), name='unique_screenshot_session_seq')],
            },
        ),
    ]
