# Generated by Django 6.0.7 on 2026-09-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0010_restore_audit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='ai_profile',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='examsession',
            name='camera_check',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examsession',
            name='proctoring_state',
            field=models.CharField(choices=[('idle', 'Boshlanmagan'), ('camera_check', 'Kamera tekshiruvida'), ('ready', 'Tayyor'), ('starting', 'Ishga tushmoqda'), ('active', 'Faol'), ('degraded', 'Cheklangan rejim'), ('paused', "To'xtatib turilgan"), ('finishing', 'Yakunlanmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Muvaffaqiyatsiz')], db_index=True, default='idle', max_length=12),
        ),
        migrations.AddField(
            model_name='examsession',
            name='risk_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='camera_role',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='evidence_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='track_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proctoringevent',
            name='type',
            field=models.CharField(choices=[('window_blur', 'Oynadan chiqish'), ('window_focus', 'Oynaga qaytish'), ('fullscreen_exit', "To'liq ekrandan chiqish"), ('hotkey_blocked', 'Tezkor tugma bloklandi'), ('clipboard_blocked', "Nusxa ko'chirish bloklandi"), ('multi_monitor', 'Bir nechta monitor'), ('camera_lost', "Kamera yo'qoldi"), ('camera_blocked', 'Kamera yopilgan'), ('rdp_detected', 'Masofaviy boshqaruv aniqlandi'), ('vm_detected', 'Virtual mashina aniqlandi'), ('process_blacklisted', 'Taqiqlangan dastur'), ('face_not_found', 'Yuz topilmadi'), ('face_mismatch', 'Yuz mos kelmadi'), ('multiple_faces', 'Bir nechta yuz'), ('object_detected', 'Taqiqlangan obyekt'), ('face_occluded', 'Yuz qisman yopilgan'), ('face_too_far', 'Yuz juda uzoqda'), ('face_too_close', 'Yuz juda yaqin'), ('student_left_frame', 'Talabgor kadrdan chiqdi'), ('second_person', 'Kadrda ikkinchi odam'), ('looking_away', 'Chetga qaradi'), ('prolonged_looking_away', 'Uzoq vaqt chetga qaradi'), ('excessive_head_movement', "Bosh harakati ko'p"), ('eyes_closed', "Ko'zlar yumuq"), ('hand_below_desk', "Qo'l stol ostida"), ('suspicious_hand_movement', "Shubhali qo'l harakati"), ('unauthorized_device', 'Ruxsatsiz qurilma'), ('high_suspicion_phone', 'Yuqori shubha - telefon'), ('high_suspicion_person', 'Yuqori shubha - begona shaxs'), ('high_suspicion_identity', 'Yuqori shubha - shaxs almashtirilgan'), ('camera_degraded', 'Kamera sifati pasaydi'), ('camera_reconnected', 'Kamera qayta ulandi'), ('proctoring_degraded', 'Kuzatuv cheklangan rejimda'), ('network_lost', 'Tarmoq uzildi'), ('network_restored', 'Tarmoq tiklandi'), ('client_anomaly', 'Client anomaliyasi'), ('navigation_blocked', 'URL bloklandi'), ('proctor_warning', 'Proktor ogohlantirdi'), ('session_terminated', 'Sessiya tugatildi')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('frame', 'Kadr'), ('clip', 'Video klip')], default='frame', max_length=8, verbose_name='Turi')),
                ('storage', models.CharField(choices=[('fs', 'Fayl tizimi'), ('s3', 'Obyekt storage')], default='fs', max_length=4, verbose_name='Saqlash')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name="Fayl yo'li")),
                ('object_key', models.CharField(blank=True, default='', max_length=500)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=64, verbose_name='MIME turi')),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=48, verbose_name='Hodisa turi')),
                ('camera_role', models.CharField(blank=True, default='', max_length=10, verbose_name='Kamera roli')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='Ishonch')),
                ('boxes', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='Olingan vaqti')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_committed', models.BooleanField(db_index=True, default=False)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='proctoring.examsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Dalil',
                'verbose_name_plural': 'Dalillar',
                'db_table': 'evidence_artifact',
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['session', '-captured_at'], name='idx_evidence_session_time'), models.Index(fields=['is_committed', 'purge_after'], name='idx_evidence_purge'), models.Index(fields=['session', 'event_type'], name='idx_evidence_session_type')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('file_path', ''), _negated=True), fields=('file_path',), name='unique_evidence_file_path'), models.UniqueConstraint(condition=models.Q(('object_key', ''), _negated=True), fields=('object_key',), name='unique_evidence_object_key'), models.CheckConstraint(condition=models.Q(models.Q(('storage', 'fs'), models.Q(('file_path', ''), _negated=True)), models.Q(('storage', 's3'), models.Q(('object_key', ''), _negated=True)), _connector='OR'), name='evidence_storage_path_present')],
            },
        ),
    ]
