# Generated by Django 6.0.7 on 2026-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0016_score_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverificationlog',
            name='reference_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
