# Generated by Django 6.0.7 on 2026-09-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0017_face_reference_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRecording',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('screen', 'Ekran yozuvi'), ('clip', 'Kamera klipi')], db_index=True, default='screen', max_length=8, verbose_name='Turi')),
                ('local_path', models.CharField(max_length=500, verbose_name="Mashinadagi yo'l")),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (ms)')),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('frames', models.PositiveIntegerField(default=0)),
                ('frames_dropped', models.PositiveIntegerField(default=0)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Qurilma')),
                ('machine_mac', models.CharField(blank=True, default='', max_length=32, verbose_name='MAC manzil')),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=48, verbose_name='Hodisa turi')),
                ('camera_role', models.CharField(blank=True, default='', max_length=10, verbose_name='Kamera roli')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='Ishonch')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='Olingan vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_recordings', to='proctoring.examsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Mashinadagi yozuv',
                'verbose_name_plural': 'Mashinadagi yozuvlar',
                'db_table': 'local_recording',
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['session', '-captured_at'], name='idx_localrec_session')],
                'constraints': [models.UniqueConstraint(fields=('session', 'local_path'), name='unique_local_recording_path')],
            },
        ),
    ]
