# Generated by Django 6.0.7 on 2026-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0019_camera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringscreenshot',
            name='question_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Savol ID'),
        ),
        migrations.AddField(
            model_name='proctoringscreenshot',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Savol raqami'),
        ),
        migrations.AddField(
            model_name='screenshotmeta',
            name='question_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Savol ID'),
        ),
        migrations.AddField(
            model_name='screenshotmeta',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Savol raqami'),
        ),
        migrations.AddIndex(
            model_name='screenshotmeta',
            index=models.Index(fields=['session', 'question_id'], name='idx_shot_session_question'),
        ),
        migrations.AddConstraint(
            model_name='proctoringscreenshot',
            constraint=models.UniqueConstraint(condition=models.Q(('question_id', ''), _negated=True), fields=('session', 'question_id'), name='unique_screenshot_session_question'),
        ),
    ]
