# Generated by Django 6.0.7 on 2026-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0020_screenshot_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='machine_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
